(* token hashtable used to reduce the states of the Finite Automaton generated by ocamllex *)
open Tokens

let keyword_table = 
  let
    create_hashtable size init =
      let tbl = Hashtbl.create size in
      List.iter (fun (key, data) -> Hashtbl.add tbl key data) init;
      tbl
  in
  create_hashtable 17 [
    ("and",       AND     );
    ("char",      CHAR    );
    ("div",       DIV     );
    ("do",        DO      );
    ("else",      ELSE    );
    ("fun",       FUN     );
    ("if",        IF      );
    ("int",       INT     );
    ("mod",       MOD     );
    ("not",       NOT     );
    ("nothing",   NOTHING );
    ("or",        OR      );
    ("ref",       REF     );
    ("return",    RETURN  );
    ("then",      THEN    );
    ("var",       VAR     );
    ("while",     WHILE   );
  ]